<?php

function hovercraft_google_fonts_array() {

$googlefontslist = array(
    'arvo' => 'Arvo',
    'averia_libre' => 'Averia Libre',
    'battambang' => 'Battambang',
    'bebas_neue' => 'Bebas Neue',
    'bitter' => 'Bitter',
    'bungee_inline' => 'Bungee Inline',
    'carter_one' => 'Carter One',
    'caveat' => 'Caveat',
    'caveat_brush' => 'Caveat Brush',
    'chewy' => 'Chewy',
    'chocolate_classical_sans' => 'Chocolate Classical Sans',
    'cormorant_garamond' => 'Cormorant Garamond',
    'courgette' => 'Courgette',
    'crete_round' => 'Crete Round',
    'crimson_text' => 'Crimson Text',
    'dai_banna_sil' => 'Dai Banna SIL',
    'dancing_script' => 'Dancing Script',
    'eb_garamond' => 'EB Garamond',
    'fredoka_one' => 'Fredoka One',
    'genos' => 'Genos',
    'gentium_book_plus' => 'Gentium Book Plus',
    'gloria_hallelujah' => 'Gloria Hallelujah',
    'hanuman' => 'Hanuman',
    'itim' => 'Itim',
    'kanit' => 'Kanit',
    'knewave' => 'Knewave',
    'krub' => 'Krub',
    'lato' => 'Lato',
    'libre_baskerville' => 'Libre Baskerville',
    'lilita_one' => 'Lilita One',
    'lisu_bosa' => 'Lisu Bosa',
    'lobster' => 'Lobster',
    'lora' => 'Lora',
    'ma_shan_zheng' => 'Ma Shan Zheng',
    'mali' => 'Mali',
    'marcellus_sc' => 'Marcellus SC',
    'merriweather' => 'Merriweather',
    'monoton' => 'Monoton',
    'montserrat' => 'Montserrat',
    'nokora' => 'Nokora',
    'noto_sans' => 'Noto Sans',
    'noto_serif' => 'Noto Serif',
    'open_sans' => 'Open Sans',
    'orbitron' => 'Orbitron',
    'pacifico' => 'Pacifico',
    'padauk' => 'Padauk',
    'permanent_marker' => 'Permanent Marker',
    'phudu' => 'Phudu',
    'playfair_display' => 'Playfair Display',
    'poller_one' => 'Poller One',
    'poppins' => 'Poppins',
    'press_start_2p' => 'Press Start 2P',
    'pridi' => 'Pridi',
    'prompt' => 'Prompt',
    'pt_serif' => 'PT Serif',
    'raleway' => 'Raleway',
    'rancho' => 'Rancho',
    'righteous' => 'Righteous',
    'roboto' => 'Roboto',
    'roboto_slab' => 'Roboto Slab',
    'rowdies' => 'Rowdies',
    'rubik' => 'Rubik',
    'rye' => 'Rye',
    'sarabun' => 'Sarabun',
    'source_serif_pro' => 'Source Serif Pro',
    'special_elite' => 'Special Elite',
    'staatliches' => 'Staatliches',
    'tektur' => 'Tektur',
    'titan_one' => 'Titan One',
    'yellowtail' => 'Yellowtail',
    'zcool_qingke_huangyou' => 'ZCOOL QingKe HuangYou',
    'zen_dots' => 'Zen Dots',
    'zilla_slab' => 'Zilla Slab'
);

return $googlefontslist;
}

// https://stackoverflow.com/questions/57558027/how-to-access-an-array-variable-from-another-php-file-in-wordpress
